# Generated by Django 5.0.6 on 2024-07-30 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stakeholder_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stakeholder_name', models.CharField(max_length=100, null=True)),
                ('stakeholder_address', models.CharField(max_length=200, null=True)),
                ('stakeholder_mobile', models.CharField(max_length=15, null=True)),
                ('stakeholder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stakeholder_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
