# Generated by Django 5.0.6 on 2024-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stakeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='stakeholder_address',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='stakeholder_email',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='stakeholder_mobile',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='stakeholder_name',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='stakeholder_type',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=128, null=True),
        ),
    ]
