# Generated by Django 5.0.6 on 2024-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_stakeholder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Supplier', 'Supplier')], max_length=128, null=True),
        ),
    ]
