# Generated by Django 5.0.6 on 2024-10-06 07:29

from django.db import migrations, models


def alter_stakeholder_id(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
            ALTER TABLE accounts_stakeholder
                DROP CONSTRAINT accounts_stakeholder_pkey;
            ALTER TABLE accounts_stakeholder DROP COLUMN id;
            ALTER TABLE accounts_stakeholder
                ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
        ''')

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_stakeholder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='auto_id',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    alter_stakeholder_id,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='stakeholder',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
