# Generated by Django 5.0.6 on 2024-10-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_stakeholder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='auto_id',
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
