# Generated by Django 5.0.6 on 2024-12-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_stakeholder_auto_id_alter_stakeholder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='opening_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
