# Generated by Django 5.0.6 on 2024-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER TABLE inventory_product
                            DROP CONSTRAINT inventory_product_pkey;
                        ALTER TABLE inventory_product DROP COLUMN id;
                        ALTER TABLE inventory_product
                            ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                    ''',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='product',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
