# Generated by Django 5.0.6 on 2024-10-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auto_id',
        ),
    ]
