# Generated by Django 5.0.6 on 2024-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_orderitem_payment_return_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
