# Generated by Django 5.0.6 on 2024-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_order_pending_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Recieved', 'Recieved'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Recieved', max_length=20),
            preserve_default=False,
        ),
    ]
