# Generated by Django 5.0.6 on 2024-10-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_status_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Recieved', 'Recieved'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Issued', 'Issued')], default='Issued', max_length=20),
        ),
    ]
