# Generated by Django 5.0.6 on 2024-10-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price_at_time_of_purchase',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
