# Generated by Django 5.0.6 on 2024-10-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pieces', 'Pieces'), ('Kilograms', 'Kilograms'), ('Sets', 'Sets')], max_length=100, null=True),
        ),
    ]
