# Generated by Django 5.0.6 on 2024-10-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_return_original_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='original_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='price_at_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
