# Generated by Django 5.0.6 on 2024-11-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pending_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
