# Generated by Django 5.0.6 on 2024-12-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_stakeholder_auto_id_alter_stakeholder_id'),
        ('inventory', '0019_alter_order_pending_amount_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.stakeholder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.order'),
        ),
    ]
