# Generated by Django 5.0.6 on 2024-12-03 01:13

from django.db import migrations

def populate_company(apps, schema_editor):
    # Get the Payment and Order models
    Payment = apps.get_model('inventory', 'Payment')
    Order = apps.get_model('inventory', 'Order')

    # Iterate through each Payment instance
    for payment in Payment.objects.all():
        # If the payment is linked to an order, populate the company field
        if payment.order and payment.order.stakeholder:
            payment.company = payment.order.stakeholder
            payment.save()
            print(f"Payment {payment.id} updated with company {payment.order.stakeholder}")

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_payment_company_alter_payment_order'),
    ]

    operations = [
        migrations.RunPython(populate_company, migrations.RunPython.noop),
    ]
