# Generated by Django 5.0.4 on 2026-09-01 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_purchased',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_sold',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productsize'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase Order Receipt'), ('SALE', 'Sales Order Shipment'), ('RETURN_SALE', 'Sales Return'), ('RETURN_PURCHASE', 'Purchase Return'), ('ADJUSTMENT', 'Stock Adjustment'), ('TRANSFER', 'Internal Transfer')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.order')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.productsize')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
