# Generated by Django 5.0.4 on 2026-09-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_simplify_inventory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productsize'),
        ),
    ]
