# Generated by Django 5.0.4 on 2026-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_add_product_size_to_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='return_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processed', 'Processed'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='stock_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Defective', 'Defective'), ('Wrong Item', 'Wrong Item')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
