# Generated by Django 5.0.4 on 2026-09-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_payment_created_at_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='price_at_time_of_purchase',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
